# Generated by Django 4.0.4 on 2022-04-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.TextField(max_length=50),
        ),
    ]
