# Generated by Django 4.0.4 on 2022-04-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_image_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.TextField(null=True),
        ),
    ]
